from .utils.ALIGNManager import ALIGNManager
from .utils.MLPManager import MLPManager

from models.ram.models import ram
from models.ram.models import tag2text
from models.ram import inference_ram
from models.ram import inference_tag2text
from models.ram import get_transform

import torch
import os

device = 'cuda' if torch.cuda.is_available() else 'cpu'

mlp_model = MLPManager()

# MM Models
align_model = ALIGNManager(device)


RAM_WEIGHTS = os.path.join(os.path.dirname(__file__), 'weights/ram_swin_large_14m.pth')
T2T_WEIGHTS = os.path.join(os.path.dirname(__file__), 'weights/tag2text_swin_14m.pth')

# RAM
IMAGE_SIZE = 384
ram_model = ram(pretrained=RAM_WEIGHTS, image_size=IMAGE_SIZE, vit='swin_l')
ram_model = ram_model.to(device)
ram_model.eval()

# T2T
t2t_model = tag2text(pretrained=T2T_WEIGHTS, image_size=IMAGE_SIZE, vit='swin_b')
t2t_model = t2t_model.to(device)
t2t_model.threshold = 0.68
t2t_model.eval()


def generate_caption(image) -> str:
    """
    Generate caption from image using Recognize Anything Model (RAM) and Tag2Text (T2T) model.

    INPUT:
    ------------------------------------
    image (PIL.Image): 
                        Image to generate caption from.
    
    RETURNS:
    ------------------------------------
    caption (str):      
                        Generated caption.
    """
    transform = get_transform(image_size=IMAGE_SIZE)
    image = transform(image).unsqueeze(0).to(device)

    tags = inference_ram(image, ram_model)
    _, _, caption = inference_tag2text(image, t2t_model, tags) # [Model identified tags, RAM generated tags, caption]

    return caption
    
# TODO: Model select
def generate_image_query(query, model=0):
    """
    Generate image query from image using the specified model.

    INPUT:
    ------------------------------------
    query (PIL.Image):
                        Query image.
    
    model (int):
                        Model to use for query.
                        0 for ALIGN, 1 for ALIGN + MLP, 2 for ALIGN + Hybrid, 3 for ALIGN + Hybrid + Split.

    RETURNS:
    ------------------------------------
    query_embedding (np.ndarray):
                        Embedding of the input image generated by the specified model.
    
    caption (str):
                        Caption generated by Recognize Anything Model (RAM) and Tag2Text (T2T) model.

    """

    if model == 0:
        raise NotImplementedError
    elif model == 1:
        raise NotImplementedError
    elif model == 2:
        raise NotImplementedError
    elif model == 3:
        model = align_model
    else:
        raise KeyError("Invalid model selection")

    caption = generate_caption(query)
    return model.get_single_image_embedding(query), caption
    
# TODO: Model select
def generate_text_query(query, model=0):
    """
    Generate text query from text using the specified model.

    INPUT:
    ------------------------------------
    query (str):
                        Query text.
    
    model (int):
                        Model to use for query.
                        0 for ALIGN, 1 for ALIGN + MLP, 2 for ALIGN + Hybrid, 3 for ALIGN + Hybrid + Split.
    
    RETURNS:
    ------------------------------------
    query_embedding (np.ndarray):
                        Embedding of the input text generated by the specified model.
    
    query (str):
                        Query text.
    """
    if model == 0:
        raise NotImplementedError
    elif model == 1:
        raise NotImplementedError
    elif model == 2:
        raise NotImplementedError
    elif model == 3:
        model = align_model
    else:
        raise KeyError("Invalid model selection")

    return model.get_single_text_embedding(query), query
    
print("Models loaded") # TODO: Replace with logger